# Generated by Django 6.0.5 on 2026-08-25 10:41

import django.core.validators
import django.utils.timezone
import uuid
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='verification_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), website.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='leader',
            name='photo',
            field=models.ImageField(blank=True, upload_to='leaders/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), website.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
